services:
  - type: web
    name: civicsafe-3d
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://mukherjeesayan2763_db_user:Sayan@1965@cluster0.0xk2h2u.mongodb.net/?appName=Cluster0
